osx_image: xcode7
language: objective-c

install:
  - bundle install --without=documentation
  - cd ActorKit && bundle exec pod install && cd $TRAVIS_BUILD_DIR

script:
  - bundle exec rake

after_success:
  - bundle exec rake coverage
